version: '3.9' # docker version

services:

  #project name 
  phpApp:
    depends_on:
      - mysql

    image: php:apache # setting up the environment: PHP running on Apache server  (latest version)
    volumes:
      # sync PHP code with Docker - map: ./ (the current root folder) to /var/www/html (path to Docker container)
      - "./:/var/www/html"
    ports:
      - 80:80 # default port for localhost
      - 443:443 # for future ssl

    #connect Docker to dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - edge
 

  # MySQL Service
  mysql:
    image: mysql:latest

    environment:
      - MYSQL_DATABASE=db_name # name for database  (the database will be created automatically)
      - MYSQL_USER=isladjan # user name for mysql
      - MYSQL_ROOT_PASSWORD=strongrootpassword #password for the MySQL root account
      - MYSQL_PASSWORD=strongrootpassword2 # password for mysql
    #      - MYSQL_ALLOW_EMPTY_PASSWORD=1          # allow empty password
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    networks:
      - edge

  # phpMyAdmin Service
  phpmyadmin:
    depends_on:
      - mysql
      
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - edge

# enable all Containers to work together
networks:
  edge:
    driver: bridge



